.create table tableserre (dateTime: datetime, temperature: double, distance: double, percentageDoorOpen: double)

.create table tableserre ingestion json mapping 'jsonmappingserre' '[{"column":"dateTime","Properties":{"path":"$.dateTime"}},{"column":"temperature","Properties":{"path":"$.temperature"}},{"column":"distance","Properties":{"path":"$.distance"}},{"column":"percentageDoorOpen","Properties":{"path":"$.percentageDoorOpen"}}]'

tableserre